name: Kubernetes Workflow
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v4
      # - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      # - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/react-test -f ./client/Dockerfile.dev ./client
      # - run: docker run -e CI=true ${{ secrets.DOCKER_USERNAME }}/react-test npm test
      - name: Place holder
        run: echo "Change gh actions"
